### ISSUE TITLE
digi

### ISSUE THREAD

**Issue by the-poor-gamer-124** [redmusicxd/iptv_ro#10] opened 2021-03-15 13:09 UTC
digi| getLogin: Invalid repetitive credentials - RMTP-1

what might cause this error?

**Comment by the-poor-gamer-124** [comment] 2021-03-15 13:13
it alternates between that & digi| getLogin: digi| login: Error: Request failed with status code 200

**Comment by the-poor-gamer-124** [comment] 2021-03-15 13:15
is it posible that digi blocked my ip?

**Comment by redmusicxd** [comment] 2021-03-15 13:23
Did you tried login on their website?

**Comment by the-poor-gamer-124** [comment] 2021-03-15 13:27
yeah i am watching something there right now.
ive changed the account and still says same thing

**Comment by the-poor-gamer-124** [comment] 2021-03-15 13:27
account in script*

**Comment by redmusicxd** [comment] 2021-03-15 13:34
Well that's unusual then, I'll investigate it when I can and get back to
you.

**Comment by the-poor-gamer-124** [comment] 2021-03-15 13:34
Ok thanks. I'll see if I can get my hands on another server..

**Comment by the-poor-gamer-124** [comment] 2021-03-15 13:48
Just random question: does any digi channel works for you? maybe they changed their API?

**Comment by redmusicxd** [comment] 2021-03-15 13:52
Actually I checked now and seems like it stopped working so I guess that's
one cause.

**Comment by the-poor-gamer-124** [comment] 2021-03-15 13:53
Hmmmmm,,,, their website ( sometimes, not always ) gives some errors, from a varnish server, maybe their origin is down?

Only time will tell, but it works on my phone, but on my pc not

**Comment by redmusicxd** [comment] 2021-03-15 13:56
Yeah well I think it is part of the redesigning process that's been going
on.

**Comment by redmusicxd** [comment] 2021-03-15 14:01
I wanted to use their api endpoints at digiapis.rcsrds.ro but it's not very
reliable this way as requires more maintainance from my side.

**Comment by the-poor-gamer-124** [comment] 2021-03-15 14:13
{"shortcode":"livestream","new-info":{"meta":{"scope":"tnt","start":"","stop":"","message":"","channelName":"TNT","streamUrl":"\/api\/stream","streamId":91,"abr":true,"balancerKey":"de7317dfd610f9180d6e912f4bba04ad","loggedIn":true}}}                </script>
  | </div>
 

But tell me more ( if you can ) about that

**Comment by redmusicxd** [comment] 2021-03-15 14:21
Yeah ,no, but if you want the endpoints I'll give you a hint, read your
phone's logs.

**Comment by the-poor-gamer-124** [comment] 2021-03-15 14:21
but is it useful for digi online, or i'll just find something else

**Comment by redmusicxd** [comment] 2021-03-15 14:23
Yes it is

**Comment by the-poor-gamer-124** [comment] 2021-03-15 14:23
ah ok thanks; ill see what i can do

**Comment by the-poor-gamer-124** [comment] 2021-03-15 14:26
digi| getLogin: Invalid repetitive credentials - RMTP-1 is the new error

**Comment by redmusicxd** [comment] 2021-03-15 14:33
It's a problem with their servers because digi.ro is also affected besides
digionline.ro.

**Comment by the-poor-gamer-124** [comment] 2021-03-15 14:33
but the sites now work as well, i am even watching something in digi online

**Comment by redmusicxd** [comment] 2021-03-15 14:40
I know, I checked earlier on my script and it is working now but if you
receive further errors it's probably their servers, try again later and if
not post a comment.

**Comment by the-poor-gamer-124** [comment] 2021-03-15 14:41
ah ok, might be the server, / asn blocked i'll see

**Comment by the-poor-gamer-124** [comment] 2021-03-15 14:48
i've also tried curl'ing their site and it works ok

**Comment by the-poor-gamer-124** [comment] 2021-03-15 14:52
am pus pe pc personal, si, ciudat, tot nu merge..

**Comment by the-poor-gamer-124** [comment] 2021-03-15 15:15
dar, in exactitate, ce inseamna digi| getLogin: Invalid repetitive credentials - RMTP-1

**Comment by the-poor-gamer-124** [comment] 2021-03-15 15:49
dar nu cand este o eroare

**Comment by the-poor-gamer-124** [comment] 2021-03-15 15:55
{"shortcode":"livestream","new-info":{"meta":{"scope":"filmcafe","start":"","stop":"","message":"","channelName":"Film Cafe","streamUrl":"\/api\/stream","streamId":94,"abr":true,"balancerKey":"d3d488d0594bebc5d3689cb4e9554000","loggedIn":true}}}                </script>
 

S-a schimbat codul ce incarca canalul

**Comment by the-poor-gamer-124** [comment] 2021-03-15 16:55
ptr mine inca nu functioneaza, din pacate.

**Comment by the-poor-gamer-124** [comment] 2021-03-20 11:25
digi changed their api, that's why it isn't working

**Comment by redmusicxd** [comment] 2021-03-20 11:52
I’m a bit sick these days so I’m not able to make code modifications but as you can see below the code is working so I’m not sure what is the problem.

https://user-images.githubusercontent.com/29458132/111868502-eb37f980-8982-11eb-8bda-162d8354af12.MP4

Closing the issue as the problem can’t be reproduced.

**Closed by redmusicxd** 2021-03-20 11:52 UTC

**Comment by the-poor-gamer-124** [comment] 2021-03-20 12:30
Ciudat, la mine ( pe server ) nu merge de nici o culoare. Am incercat diverse conturi, schimbare ip, versiuni mai vechi, nimic nu merge.

**Comment by the-poor-gamer-124** [comment] 2021-03-21 09:52
<?php
function limita($text,$inceput,$sfarsit)
{
$rezultat=explode($inceput,$text);
$rezultat=$rezultat[1];
$rezultat=explode($sfarsit,$rezultat);
return $rezultat[0];
}

$idpost=$_GET['id'];
$postdata = http_build_query(
    array(
        'id_stream' => $idpost,
        'quality' => 'abr'
    )
);
$opts = [
    "http" => [
        "method" => "POST",
        "header" => "Accept-language: en\r\n" .
            "Cookie: DOSESSV3PRI=2385044ED49443A4B044FC9EB3427163D722D4A85EC542DD; deviceId=bad2103a68f079eb8728ff75b2498275.Microsoft_Edge_88_0_Windows_943c05d78ebf47735a270e56d01daef8_PCBROWSER; recentTvChannelIDs=1391.1435\r\n" .
			"User-Agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Mobile Safari/537.36\r\n",
			'content' => $postdata
    ]
];

$context = stream_context_create($opts);
$curl=file_get_contents("https://www.digionline.ro/api/stream", false, $context);
$data = json_decode($curl,true);
$aflaurl = $data['stream_url'];
$numeTV=limita($aflaurl,"ns=","&");
$explode=explode('/',$aflaurl);
$server=$explode[2];
$token=$explode[3];
$sesiune=$explode[4];
//////////////////////Incepe verificarea postului tv

$viaurl = [
    "http" => [
        "method" => "GET",
        "header" => "Accept-language: en\r\n" .
            "Cookie: DOSESSV3PRI=; deviceId=; recentTvChannelIDs=1391.1435\r\n" .
			"User-Agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Mobile Safari/537.36\r\n"
    ]
];

$m3u8 = stream_context_create($viaurl);
$link=file_get_contents($aflaurl, false, $m3u8);

$calitate=limita($link,"".$numeTV."",".");
$creazatoken="https://".$server."/".$token."/".$sesiune."/".$numeTV."".$calitate.".stream/chunklist.m3u8";

echo ".$creazatoken.";
die();


Am facut rost de acest cod ptr a grabui DIGI ONLINE, cand ai timp, poate te poti uita peste el.

**Comment by the-poor-gamer-124** [comment] 2021-03-21 09:55
[tktv.txt](https://github.com/redmusicxd/iptv_ro/files/6177162/tktv.txt)

**Comment by the-poor-gamer-124** [comment] 2021-03-21 09:56
[tktv.txt](https://github.com/redmusicxd/iptv_ro/files/6177166/tktv.txt)

**Comment by redmusicxd** [comment] 2021-03-21 10:51
I took a look at your code and it's basically what my JavaScript code does
except it does some redundant thing at the end of the code, I doesn't make
sense to build the URL based on the received URL as you end up with the
same link.

**Comment by the-poor-gamer-124** [comment] 2021-03-22 14:49
Yet it does not work either...

**Comment by redmusicxd** [comment] 2021-03-23 18:46
Sorry for the late reply, I have some free time on weekend and so we can
see then what can be done to solve this issue if that's ok with you.

**Comment by the-poor-gamer-124** [comment] 2021-03-23 19:08
Ive fixed it... by waiting..

now it works

mar., 23 mar. 2021, 20:46 Dan Negru ***@***.***> a scris:

**Comment by redmusicxd** [comment] 2021-03-23 19:19
Ok then, glad it's working now.

**Comment by the-poor-gamer-124** [comment] 2021-03-23 20:15
Maybe when you have free time you can make it run a little smother. I've moved to a dedicated server, yet it still works kindof slowly...

**Comment by the-poor-gamer-124** [comment] 2021-03-25 16:53
But i do have to mention i do a lot of calls to it..
