### ISSUE TITLE
Digi

### ISSUE THREAD

**Issue by the-poor-gamer-124** [redmusicxd/iptv_ro#7] opened 2021-02-05 22:56 UTC
For digi errors,

Maybe cache can be purged, not too often, but when the error appears. This way it uses less reousrces but does still work. 

Or instead keep no cache since the tokens are very low lasting now :(

**Comment by the-poor-gamer-124** [comment] 2021-02-05 22:57
And also trying to get digisport not from digi online won't work

**Comment by the-poor-gamer-124** [comment] 2021-02-06 07:28
Also, since AMINO is now secured :(, a EPG would be useful ig? 

I've made a parser to the old amino which shows now & next with a STB-ish UI
[program-tv.zip](https://github.com/redmusicxd/iptv_ro/files/5936444/program-tv.zip)

**Comment by redmusicxd** [comment] 2021-02-06 11:47
yeah well unfortunately it doesn't work
![image](https://user-images.githubusercontent.com/29458132/107117271-dfd0b900-6881-11eb-9e04-56a6085b3e8a.png)

**Comment by redmusicxd** [comment] 2021-02-06 11:48
also i found when i was scrubing the tv channels id's that digi-online has a epg api like this https://www.digionline.ro/epg-xhr?channelId=30

**Comment by redmusicxd** [comment] 2021-02-06 12:01
as for the 401 error seems like i commented out the line that sets a timeout for deleting object with the url and forgot to put it back

**Comment by the-poor-gamer-124** [comment] 2021-02-06 12:13
thanks for the epg API

**Comment by the-poor-gamer-124** [comment] 2021-02-06 12:16
> yeah well unfortunately it doesn't work
> ![image](https://user-images.githubusercontent.com/29458132/107117271-dfd0b900-6881-11eb-9e04-56a6085b3e8a.png)

yes it was made for amino

**Comment by the-poor-gamer-124** [comment] 2021-02-06 12:24
i've found out the hard way that caching the tokens is only useless

**Comment by redmusicxd** [comment] 2021-02-06 12:32
yeah well it was intended so it doesn't request a new url on every request but now when i think about it, it doesn't make sense if you don't proxy the segment files.

**Comment by the-poor-gamer-124** [comment] 2021-02-06 12:34
i actually have a proxy that works with dynamic https://proxy.canale.live/stream.php?url=https://edge213.rcs-rds.ro/V5-1250823-53a43010558f1c3956002a346eeb4182-3111686696-0-1612614844-1-digisport1-0877f7addc73df76/digionline/digisport1hq.stream/media-uz5np4ccq_77123.ts

**Comment by redmusicxd** [comment] 2021-02-06 12:48
alright, I'll integrate that right away

**Comment by the-poor-gamer-124** [comment] 2021-02-06 12:49
the proxy is insxtable tho

**Comment by redmusicxd** [comment] 2021-02-06 13:00
what do you mean?

**Comment by the-poor-gamer-124** [comment] 2021-02-06 13:05
it has a lot of downtime from time to time

**Comment by the-poor-gamer-124** [comment] 2021-02-06 13:29
de asemenea, digisporturi fara digi online nu merg, nada, nilch

**Comment by redmusicxd** [comment] 2021-02-06 13:42
adica?, la mine nu sunt probleme

**Comment by the-poor-gamer-124** [comment] 2021-02-06 13:44
hmmm, ciudat

**Comment by redmusicxd** [comment] 2021-02-06 13:46
dai un pul acuml, commit-ul 0327dbe0eecc2a8ba3b16c6104499cb3deae8355 elimina stocarea url-ului daca nu folosesti parametrul ts

**Comment by the-poor-gamer-124** [comment] 2021-02-06 14:27
pai si pe TS param TS era problema

**Comment by the-poor-gamer-124** [comment] 2021-02-06 15:02
cum as putea sa scot cache la TS uri ( ca e inutil, tot aceleasi probleme face )

**Comment by redmusicxd** [comment] 2021-02-06 15:14
uite 176fd2f62719d096e9a784e8da3c417a50c9c04f , nu este inutil, este o metoda de precautiune sa nu zica ceva digi ca faci prea multe cereri, daca nu salvez link-ul atunci ar fi echivalentul unui refresh la pagina pe digionline (deci de fiecare data o alta cerere pentru link catre stream)

**Comment by the-poor-gamer-124** [comment] 2021-02-06 15:15
ah, mersi totusi :)

**Comment by the-poor-gamer-124** [comment] 2021-02-06 15:17
si oricum, la viata lunga unui token, nici nu cred ca ar fi alta optiune

**Comment by redmusicxd** [comment] 2021-02-06 15:19
pai da, a doua zi nu mai poti folosi acelasi base URL, asa ca am pus sa stearga dupa 6 ore

**Comment by redmusicxd** [comment] 2021-02-12 14:49
closing the issue as the reported issue has been fixed since

**Closed by redmusicxd** 2021-02-12 14:49 UTC
